### ISSUE TITLE
Video Sensing 

### ISSUE THREAD

**Issue by limsherwin** [scratux/scratux#16]
Hello, 

Currently using Scratux on Ubuntu 20.  Video sensing can't seem to turn on the webcam.

Using the same machine, I tested using MIT Scratch 3 with the browser. It was able to turn on and use  the webcam with sample codes.

Is this a bug or is there some permissions in have to set?

**Comment by joancipria** [comment]
Hi @limsherwin and thanks for reporting. Are you using the snap version?

**Comment by limsherwin** [comment]
@joancipria Yes, I installed using snap.

**Comment by joancipria** [comment]
This is a known issue: auto-connect is not available for the `camera` interface (for security reasons) so you will need to manually connect it by `sudo snap connect scratux:camera`. Then restart Scratux and it should be working. See wiki for more info: https://github.com/scratux/scratux/wiki/Known-Issues#camera--webcam-is-not-working-on-the-snap-
version

Since this is a common question I will add manual instructions in the snap.

**Comment by limsherwin** [comment]
@joancipria 
It didn't occur to me to check the wiki for documentation.
I just searched the open/closed Issues.
Got it working now. Kids are happy. :)
Thank you.
