### ISSUE TITLE
Can't install on Pi3B+

### ISSUE THREAD

**Issue by cymplecy** [scratux/scratux#4]
Tried to install
scratux_1.1.0_armv7l.deb

using 

`sudo dpkg -i scratux_1.1.0_armv7l.deb`

and got this error msg

```
error processing archive scratux_1.1.0_armv7l.deb (--install):
 package architecture (armv7l) does not match system (armhf)
Errors were encountered while processing:
 scratux_1.1.0_armv7l.deb

```

**Comment by joancipria** [comment]
Hi @cymplecy , you have to run `sudo dpkg --add-architecture armv7l` before trying to install the package. This should fix the error.

**Comment by joancipria** [comment]
Hi @cymplecy and  thank you so much for the report. I can confirm the bug and I'm currently working on it. Some useful info: https://github.com/electron-userland/electron-builder/issues/1230 and https://github.com/electron/electron/issues/16205

**Comment by LucasVanHaaren** [comment]
I have the same bug on my pi. 
Is there a version of electron-builder allowing to build an app for raspberry right now?
(I am in 20.38.2)

**Comment by joancipria** [comment]
Hi @LucasVanHaaren, the current version of electron-builder is able to build for Raspberry so I think that's not the problem. Apparently it looks like there are 2 main problems:

- First, the architecture problem reported by @cymplecy can be solved easily by running `sudo dpkg --add-architecture armv7l` before installing the package. This workaround lets you install Scratux on a Raspberry Pi (with some dependency problems that I will explain later). So in order to avoid this tedious step to users [I added the armhf architecture to the `package.json`](https://github.com/scratux/scratux-desktop/commit/1af89f0655f0aa0c0534c35dee490219c86f7929) on the new [develop-armv7l](https://github.com/scratux/scratux-desktop/tree/develop-armv7l) branch. Thus, this problem is already solved (and tested). See https://github.com/electron-userland/electron-builder/issues/1230#issuecomment-491494976 for more info.
- On the other hand the dependency problems mentioned before are because Scratch Desktop uses `Electron 4.0.1` instead of the newest `5.0.1`, producing a `glibc` dependency problem (see https://github.com/electron/electron/issues/16205) on latest Raspbian version. I tried to update it to `5.0.1` [(which should solve the problem)](https://github.com/electron/electron/issues/16205#issuecomment-488622229) but it breaks some things ( see [breaking-changes](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md) ) so I need some more time to fix theese breaking changes.

I would try to fix this during next days, all work will be done on the new [develop-armv7l](https://github.com/scratux/scratux-desktop/tree/develop-armv7l) branch (which is already using `Electron 5.0.1`). 

Thanks for you collaboration @cymplecy  @LucasVanHaaren !

**Comment by joancipria** [comment]
I've made some progress, both commits https://github.com/scratux/scratux-desktop/commit/1af89f0655f0aa0c0534c35dee490219c86f7929 and https://github.com/scratux/scratux-desktop/commit/956b863399e7bfb8ea6d925f9015299531c4d8b8 fix the mentioned problems: Now I'm able to install Scratux on a RaspberryPi out of the box without any problem and the app starts correctly showing the loading screen. But then it splashes a blank screen until it trhows a segment violation that kills the app. I'll continue working on it.

If you want to test the current work you can download my build https://send.firefox.com/download/5aab734af33fcad6/#09rhJElY9j0F7JRj8kI16Q or build it by yourself by just adding the `armv7l` parameter to the fetch script.

`$ git clone https://github.com/scratux/scratux.git`
`$ cd scratux`
`$ git checkout master`
`$ chmod +x fetch.sh`
`$ ./fetch.sh armv7l`

Then build it by 

`$ cd src`
`$ yarn run dist // or npm run dist`

**Comment by joancipria** [comment]
Hi! Next Scratux v1.3 release (wich is going to be published this weekend) will be available for Raspberry Pi (Raspbian), so finally armv7l branch is working and builds are running perfect. Stay tuned!
![2020-02-27-192830_1824x984_scrot](https://user-images.githubusercontent.com/16108809/75479830-7d4c1900-59a0-11ea-9ea9-f57e53e70de0.png)
