### ISSUE TITLE
Version of underlying scratch-desktop

### ISSUE THREAD

**Issue by javorekm** [scratux/scratux#6]
Very nice project. Works like a charm on the first attempt. The only one thing I cannot determine is the version of the underlying scratch-desktop app. I cannot found it in the GUI. Original version is here: https://github.com/LLK/scratch-desktop/blob/develop/package.json#L6, but on the web I see the 3.4.0 now (e.g. for win: https://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.4.0.exe)

I would like to know, on which version of scratch 3 is scratux running if I install latest version from PPA e.g. for Ubuntu. Something like "scratux --version". Thanks a lot for your effort.

**Comment by joancipria** [comment]
Hi @javorekm! Thanks you so much for reporting. Currently it is based on 3.0 but I'm planning to release a new version by today or tomorrow which is based on 3.5.1. Since then you will be able to know the underlying version of Scratux by just clicking the logo on the menu bar:

![ezgif-2-526573604fbb](https://user-images.githubusercontent.com/16108809/62538483-360b0900-b853-11e9-8de4-820817f937df.gif)

**Comment by javorekm** [comment]
Looks nice! Thanks a lot.

**Comment by javorekm** [comment]
I see Scratux version 1.2 in releases, but not in repos: https://dl.bintray.com/scratux/stable/pool/s/scratux/.

**Comment by joancipria** [comment]
@javorekm That's because it is a release candidate, so it means is time for testing and finding bugs or problems. I need a couple of days to test Scratux among different linux distros and then I will push the new version to the repos. For now you can use the release candidate since I think everything is working fine.

**Comment by joancipria** [comment]
I've just published the new release, closing this issue.
